### ISSUE TITLE
希望加入我们学校的

### ISSUE THREAD

**Issue by dazhuangge** [yuxtech/cnlogo#1]
算了吧

**Comment by Freed-Wu** [comment]
你已经是一个成熟的大学生啦。自己动手试试看呗？

**Comment by dazhuangge** [comment]
我一定是自己下载过后，自己尝试，百度无果，程序报错，才会请求别人的。伸手党，不思考就提问题不是我的作风。老师若是繁忙，那便算了罢，

**Comment by dazhuangge** [comment]
我是经过思考以及尝试的

**Comment by Freed-Wu** [comment]
我没有任何指责的意思。如果你是经过尝试的我收回前面的话。
另外我不是这个仓库的主人:) 我只是提完PR刚好看到而已。不要火气那么大啦。

**Comment by dazhuangge** [comment]
> 我没有任何指责的意思。如果你是经过尝试的我收回前面的话。
> 另外我不是这个仓库的主人:) 我只是提完PR刚好看到而已。不要火气那么大啦。

抱歉抱歉

**Comment by Freed-Wu** [comment]
> > 我没有任何指责的意思。如果你是经过尝试的我收回前面的话。
> > 另外我不是这个仓库的主人:) 我只是提完PR刚好看到而已。不要火气那么大啦。
> 
> 抱歉抱歉

如果你还要尝试的话可以看一下我的PR，我写了一个方法的说明，你可以试一下。
先睡了。
